#ifndef _SMARTRF_SETTINGS_BLE_H_
#define _SMARTRF_SETTINGS_BLE_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.11.0 (build #122)
// Tested for SimpleLink SDK version: CC13x0 SDK 2.30.xx.xx
// Device: CC1350 Rev. 2.1
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ble_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define RF_BLE_TX_POWER_TABLE_SIZE 18

// TX Power Table Object
extern RF_TxPowerTable_Entry RF_BLE_txPowerTable[];

// TI-RTOS RF Mode Object
extern RF_Mode RF_modeBle;

// RF Core API commands
extern rfc_CMD_RADIO_SETUP_t RF_ble_cmdRadioSetup;
extern rfc_CMD_FS_t RF_ble_cmdFs;
extern rfc_CMD_BLE_ADV_NC_t RF_ble_cmdBleAdvNc;
extern rfc_CMD_BLE_GENERIC_RX_t RF_ble_cmdBleGenericRx;

// RF Core API Overrides
extern uint32_t pOverrides[];

#endif // _SMARTRF_SETTINGS_BLE_H_
